CREATE TABLE IF NOT EXISTS gb_admins (
    admin_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    groups VARCHAR(32) NOT NULL DEFAULT '',
    flags VARCHAR(32) NOT NULL DEFAULT '',
    immunity INT UNSIGNED NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS gb_groups (
    group_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    flags INT NOT NULL DEFAULT 0,
    group_type INT UNSIGNED NOT NULL,
    immunity INT UNSIGNED NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS gb_server_groups (
    group_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    servers VARCHAR(32) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS gb_servers (
    server_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(255) NOT NULL,
    port INT UNSIGNED NOT NULL,
    immunity INT UNSIGNED NOT NULL DEFAULT 0,
    UNIQUE KEY ip_port (ip, port)
);

CREATE TABLE IF NOT EXISTS gb_bans (
    ban_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    admin_id BIGINT UNSIGNED NOT NULL,
    server_id INT UNSIGNED NOT NULL,
    player_id BIGINT UNSIGNED NOT NULL,
    reason VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    expires_at DATETIME NOT NULL,
    comment VARCHAR(255) NULL,
    extra LONGTEXT NULL
);