CREATE TABLE IF NOT EXISTS gb_admin (
    admin_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    auths VARCHAR(255) DEFAULT '{}',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    adm_groups VARCHAR(32) NOT NULL DEFAULT '',
    web_groups VARCHAR(32) NOT NULL DEFAULT '',
    svr_groups VARCHAR(32) NOT NULL DEFAULT '',
    flags VARCHAR(32) NOT NULL DEFAULT '',
    immunity INT UNSIGNED NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS gb_group (
    group_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    flags INT NOT NULL DEFAULT 0,
    immunity INT UNSIGNED NOT NULL DEFAULT 0,
    group_type INT UNSIGNED DEFAULT 0
);

CREATE TABLE IF NOT EXISTS gb_server_group (
    group_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    servers VARCHAR(32) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS gb_server (
    server_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    app_id INT UNSIGNED NOT NULL,
    ip VARCHAR(64) NOT NULL,
    port INT UNSIGNED NOT NULL,
    immunity INT UNSIGNED NOT NULL DEFAULT 0,
    UNIQUE KEY ip_port (ip, port)
);

CREATE TABLE IF NOT EXISTS gb_bans (
    ban_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    admin_id BIGINT UNSIGNED NOT NULL,
    ban_tyoe INT UNSIGNED NOT NULL,
    server_id INT UNSIGNED NOT NULL,
    player_id BIGINT UNSIGNED NOT NULL,
    reason VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL,
    expires_at DATETIME NOT NULL,
    comment VARCHAR(255) NULL,
    extra LONGTEXT NULL
);

CREATE TABLE IF NOT EXISTS gb_application (
    application_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    image VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS gb_ban_type (
    ban_type_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);